name: Deploy to Tencent Cloud

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Generate package-lock.json
        run: npm install --package-lock-only

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=1024000"

      - name: Deploy to Tencent Cloud
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "www/**"
          target: "/www/wwwroot/49.232.186.238:1520"
          rm: false
          strip_components: 1
          overwrite: true
          command_timeout: "10m"
          timeout: "10m"
          debug: true 